# 项目管理相关
management:
  endpoints:
    web:
      exposure:
        # 开启一些 http 接口 url 出来
        include: "*"

spring:
  application:
    name: template
  jackson:
    serialization.write_dates_as_timestamps: false
  datasource:
    platform: h2
    continue-on-error: true
    type: com.zaxxer.hikari.HikariDataSource
    #url: jdbc:h2:file:./target/h2db/db/start;DB_CLOSE_DELAY=-1
    url: jdbc:h2:mem:template;DB_CLOSE_DELAY=-1
    username: template
    password:
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

info:
  project:
    version: 1.0

application:
  fileSystem:
    rootDir: F:\files
  security:
    authentication:
      jwt:
        secret: "mysecret"